data_root_dir: "/inspire/ssd/ws-f4d69b29-e0a5-44e6-bd92-acf4de9990f0/public-project/public/yjc/sunyihang/Chameleon-VLA/dataset"
run_root_dir: "runs" 
adapter_tmp_dir: "checkpoints"
learning_rate: 2e-5 
use_llm_lora: False 
use_backbone_lora: False 

 
save_steps: 400
wandb_project: "openvla"
wandb_entity: "ayakaee-sjtu"
save_latest_checkpoint_only: False
